export default {
  "/api/create": ["superadmin", "admin", "user", "bank_employee", "police"],
  "/api/upload": ["superadmin", "admin", "user"],
  "/api/uploadBalanceSheet": ["superadmin", "admin", "user"],
  "/api/deleteUser": ["admin", "police", "bank_employee", "user", "superadmin"],
  "/api/allUsers": ["superadmin", "admin", "user"],
  "/verifyAccessToken": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/inviteLink": ["superadmin", "admin", "user", "bank_employee", "police"],
  "/api/allFiles": ["superadmin", "admin", "user", "bank_employee", "police"],
  "/api/addUser": ["superadmin", "admin", "user", "bank_employee", "police"],
  "/api/getFlowData": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/getReport": ["superadmin", "admin", "user", "bank_employee", "police"],
  "/api/getReportWithBaseAmount": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/getBalanceSheetAnalysis": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/getAllAccounts": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/trackSender": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/accountDetails": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/addSuspectedAccount": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/allSuspectedAccounts": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/fraudAccounts": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/getFlowByTransaction": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/reportFraudController": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/getComplaints": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/updateComplaint": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
  "/api/createNodes": [
    "superadmin",
    "admin",
    "user",
    "bank_employee",
    "police",
  ],
};

/*
In exported JSON,
    Key: Requested API URL
    Value: Array of roles allowed to access the API
*/
